In [1]:
import torch
import numpy as np

## Tensors

In [2]:
t1 = torch.tensor(3, dtype = torch.float32)
#Torch defines 10 tensor types with CPU and GPU variants.
#Entire tensor should have same dtype like numpy.
t1

tensor(3.)

In [3]:
t2 = torch.tensor([1,2,3,4.])
print(t2)
t2.dtype

tensor([1., 2., 3., 4.])


torch.float32

In [4]:
t3 = torch.tensor(np.array([[1,2],[3,4]]))
print(t3)
t3.shape

tensor([[1, 2],
        [3, 4]])


torch.Size([2, 2])

In [5]:
#Note that it's not possible to create tensors with an improper shape.
t4 = torch.tensor([[[1,3],[5,2]], [[4,5],[3,5]]])
print(t4)
t4.shape

tensor([[[1, 3],
         [5, 2]],

        [[4, 5],
         [3, 5]]])


torch.Size([2, 2, 2])

## Tensor operations and gradients

In [6]:
#create tensors
x = torch.tensor(3.)
w = torch.tensor(4., dtype = torch.float32, requires_grad = True)
b = torch.tensor(5., requires_grad = True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [7]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

To compute the derivatives, we can invoke the .backward method on our result y

In [8]:
y.backward()

The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.

In [9]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


## Tensor functions

In [10]:
t5 = torch.full((3,2), 34, dtype = torch.float32)
t5

tensor([[34., 34.],
        [34., 34.],
        [34., 34.]])

In [11]:
t6 = torch.sin(t5)
t7 = torch.cat((t5, t6), dim = 1)
t7

tensor([[34.0000, 34.0000,  0.5291,  0.5291],
        [34.0000, 34.0000,  0.5291,  0.5291],
        [34.0000, 34.0000,  0.5291,  0.5291]])

In [12]:
t8 = torch.cat((t5, t6), dim = 0)
t8

tensor([[34.0000, 34.0000],
        [34.0000, 34.0000],
        [34.0000, 34.0000],
        [ 0.5291,  0.5291],
        [ 0.5291,  0.5291],
        [ 0.5291,  0.5291]])

In [13]:
t9 = t8.reshape((1,3,-1))
t9

tensor([[[34.0000, 34.0000, 34.0000, 34.0000],
         [34.0000, 34.0000,  0.5291,  0.5291],
         [ 0.5291,  0.5291,  0.5291,  0.5291]]])

## Interoperability with Numpy

In [14]:
array = np.array([[1,2,3],[3,5,5]])
array

array([[1, 2, 3],
       [3, 5, 5]])

In [15]:
# Convert the numpy array to a torch tensor.
tensor = torch.from_numpy(array)
tensor

tensor([[1, 2, 3],
        [3, 5, 5]])

In [16]:
array.dtype, tensor.dtype

(dtype('int64'), torch.int64)

In [17]:
# Convert a torch tensor to a numpy array
array = tensor.numpy()
array

array([[1, 2, 3],
       [3, 5, 5]])

Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.

GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.